# Generated by Django 5.1.7 on 2025-03-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CTF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("defocusu", models.FloatField()),
                ("defocusv", models.FloatField()),
            ],
        ),
    ]
