# Generated by Django 5.2 on 2025-05-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryoem_app', '0007_alter_ctf_psd_alter_micrograph_filename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='interval',
            new_name='maxres_interval',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='max_range',
            new_name='maxres_max',
        ),
        migrations.RenameField(
            model_name='config',
            old_name='min_range',
            new_name='maxres_min',
        ),
    ]
