# Generated by Django 5.2 on 2025-05-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryoem_app', '0008_rename_interval_config_maxres_interval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='color_recent_defocuscov',
            field=models.CharField(default='#544FC5', max_length=7),
        ),
        migrations.AddField(
            model_name='config',
            name='defocuscov_interval',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='config',
            name='defocuscov_max',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='config',
            name='defocuscov_min',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='config',
            name='defocuscov_recent_micrographs_count',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='config',
            name='defocuscov_special_max',
            field=models.FloatField(blank=True, default=0.1, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='defocuscov_special_min',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
