# Generated by Django 5.2 on 2025-05-31 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryoem_app', '0011_alter_ctf_defocusu_alter_ctf_defocusv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class2D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Coordinate2D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordx', models.FloatField()),
                ('coordy', models.FloatField()),
                ('score', models.FloatField()),
                ('micrograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinate', to='cryoem_app.micrograph')),
            ],
        ),
        migrations.CreateModel(
            name='Particle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_particle', models.CharField(max_length=255)),
                ('index', models.IntegerField()),
                ('sampling', models.FloatField()),
                ('rot', models.FloatField()),
                ('tilt', models.FloatField()),
                ('psi', models.FloatField()),
                ('shiftx', models.FloatField()),
                ('shifty', models.FloatField()),
                ('class2d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particle', to='cryoem_app.class2d')),
                ('coordinate2d', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='particle', to='cryoem_app.coordinate2d')),
                ('micrograph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='particle', to='cryoem_app.micrograph')),
            ],
        ),
    ]
